version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "weekly"
    groups:
      production:
        dependency-type: "production"
      development:
        dependency-type: "development"
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
