app = 'necromancer'
primary_region = 'lhr'
swap_size_mb = 1024

[[mounts]]
# IMPORTANT: You must set `PRISMA_DATABASE_URL` env var on Fly.io to point at /data
# Otherwise, data will be stored in ephemeral storage and will be lost on app restart.
source = 'bot_data'
destination = '/data'

[[vm]]
memory = 512
cpu_kind = 'shared'
cpus = 1
